[build]
  publish = "dist/"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
    cache-control = '''
    max-age=0,
    must-revalidate'''

[[headers]]
  for = "/sw.js"
  [headers.values]
    cache-control = '''
    max-age=0,
    must-revalidate'''
