name: Package Audit

on:
  push:
    branches:
      - master
    paths:
      - package.json
      - package-lock.json
  pull_request:
    branches:
      - master
    paths:
      - package.json
      - package-lock.json
  workflow_dispatch:

jobs:
  audit-npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["14"]

    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Setup Node.js environment
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Run audit
        run: npm audit --production

  audit-retire:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["14"]

    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: https://npm.pkg.github.com

      - name: Cache node modules
        uses: actions/cache@c1a5de879eb890d062a85ee0252d6036480b1fe2 # v3.2.1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node_version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node_version }}-
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install retire.js
        run: npm i -g retire

      - name: Run audit
        run: retire -n
